#!/usr/bin/env python3
"""Generate the portable Fleet Core deferred-module inventory.

The inventory is derived from the pinned upstream source tree rather than typed,
because a handwritten count is exactly what drifts. The rule is a set difference:
every item the upstream Fleet Core source carries, minus every item this portable
package actually ports. Adding a module upstream therefore fails ``--check``
until the inventory is regenerated, and no assertion anywhere depends on a
literal number.

The counting basis is stated in the generated document and implemented here:
every path under the upstream ``fleet_commons`` package, plus the
``fleet_commons_shim.py`` module beside it, split into Python modules and data
files, minus what this slice ports.

Standard library only, and no network access. Regenerating needs a local
checkout of the upstream repository at the pinned commit, which continuous
integration does not have; ``--check`` without ``--source`` therefore runs the
hermetic half of the guarantee, verifying that the recorded inventory still
agrees with what the portable package contains.

Usage::

    # Regenerate from a local upstream checkout at the pinned commit.
    generate_deferred_inventory.py --source ../infiquetra-claude-plugins/plugins/fleet-core

    # Verify the recorded inventory against that same source, writing nothing.
    generate_deferred_inventory.py --source <path> --check

    # Hermetic self-check: no upstream checkout required.
    generate_deferred_inventory.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import NamedTuple


SCRIPTS_DIRNAME = "scripts"
PACKAGE_DIRNAME = "fleet_commons"
SHIM_FILENAME = "fleet_commons_shim.py"

PYTHON_MODULE = "Python module"
DATA_FILE = "data file"

IGNORED_DIRECTORY_NAMES = ("__pycache__",)

PROVENANCE_FILENAME = "PROVENANCE.json"
DEFERRED_FILENAME = "DEFERRED.md"

GENERATED_BANNER = (
    "<!-- Generated by scripts/generate_deferred_inventory.py. Do not edit by hand. -->"
)

PORTED_HEADING = "## Ported by this package"
DEFERRED_HEADING = "## Deferred: present upstream, absent here"

# Matches a rendered inventory row: | `fleet_commons/audit_store.py` | Python module |
TABLE_ROW = re.compile(r"^\|\s*`([^`]+)`\s*\|\s*([^|]+?)\s*\|\s*$")


class InventoryError(RuntimeError):
    """Raised when a source or package tree cannot yield a trustworthy inventory."""


class Item(NamedTuple):
    """One inventoried path, named relative to a package's ``scripts`` directory."""

    name: str
    kind: str


def _classify(path: Path) -> str:
    return PYTHON_MODULE if path.suffix == ".py" else DATA_FILE


def _is_ignored(path: Path, scripts_dir: Path) -> bool:
    relative = path.relative_to(scripts_dir)
    return any(
        part in IGNORED_DIRECTORY_NAMES or part.startswith(".") for part in relative.parts
    )


def inventory(root: Path) -> list[Item]:
    """Inventory one Fleet Core package root under the stated counting basis.

    ``root`` is a package root holding ``scripts/fleet_commons/``. The shim
    module beside that package is included when present, because upstream ships
    it as part of the same surface even though it sits outside the package
    directory. A root with no ``fleet_commons`` package is an error rather than
    an empty inventory, so a mistyped path fails loudly instead of silently
    reporting that nothing exists upstream.
    """
    scripts_dir = root / SCRIPTS_DIRNAME
    package_dir = scripts_dir / PACKAGE_DIRNAME
    if not package_dir.is_dir():
        raise InventoryError(f"no {PACKAGE_DIRNAME} package under {root}: expected {package_dir}")

    items: list[Item] = []
    for path in package_dir.rglob("*"):
        if not path.is_file() or _is_ignored(path, scripts_dir):
            continue
        items.append(Item(path.relative_to(scripts_dir).as_posix(), _classify(path)))

    shim = scripts_dir / SHIM_FILENAME
    if shim.is_file():
        items.append(Item(shim.relative_to(scripts_dir).as_posix(), _classify(shim)))

    return sorted(items)


def deferred_items(upstream: list[Item], ported: list[Item]) -> list[Item]:
    """Every upstream item this package does not carry: a plain set difference."""
    ported_names = {item.name for item in ported}
    return [item for item in upstream if item.name not in ported_names]


def unknown_ported_items(upstream: list[Item], ported: list[Item]) -> list[Item]:
    """Items this package carries that the upstream source does not.

    A portable package is derived, so an item with no upstream counterpart under
    the package directory means either the pinned source is wrong or something
    was authored where a copy belongs. Either way it is reported rather than
    quietly excluded from the difference.
    """
    upstream_names = {item.name for item in upstream}
    return [item for item in ported if item.name not in upstream_names]


def read_pin(package_root: Path) -> dict[str, str]:
    """Read the pinned source coordinates from the package's provenance manifest.

    The provenance manifest is the one version source. Reading the version and
    commit from it here rather than restating them keeps the generated document
    from becoming a second place a pin can go stale.
    """
    manifest = package_root / PROVENANCE_FILENAME
    if not manifest.is_file():
        raise InventoryError(f"missing provenance manifest: {manifest}")
    try:
        payload = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise InventoryError(f"invalid provenance manifest {manifest}: {exc}") from exc
    if not isinstance(payload, dict):
        raise InventoryError(f"invalid provenance manifest {manifest}: expected an object")

    pin: dict[str, str] = {}
    for field in ("source_repository", "source_commit", "source_version"):
        value = payload.get(field)
        if not isinstance(value, str) or not value.strip():
            raise InventoryError(f"missing non-empty {field} in {manifest}")
        pin[field] = value.strip()
    return pin


def _counts(items: list[Item]) -> tuple[int, int, int]:
    modules = sum(1 for item in items if item.kind == PYTHON_MODULE)
    data = sum(1 for item in items if item.kind == DATA_FILE)
    return modules, data, len(items)


def _table(items: list[Item]) -> list[str]:
    lines = ["| Item | Kind |", "|---|---|"]
    lines.extend(f"| `{item.name}` | {item.kind} |" for item in items)
    return lines


def render(pin: dict[str, str], upstream: list[Item], ported: list[Item]) -> str:
    """Render the inventory document. Deterministic: no timestamp, sorted rows."""
    deferred = deferred_items(upstream, ported)
    upstream_counts = _counts(upstream)
    ported_counts = _counts(ported)
    deferred_counts = _counts(deferred)

    lines = [
        GENERATED_BANNER,
        "",
        "# Deferred Fleet Core modules",
        "",
        "This package ports one vertical slice of Fleet Core. Everything else the",
        "upstream source carries is named below, so no reader has to infer what is",
        "missing and no document has to claim full Fleet Core parity.",
        "",
        "## Counting basis",
        "",
        "Every path under the upstream `fleet_commons` package, plus the",
        f"`{SHIM_FILENAME}` module beside it, split into Python modules and data",
        "files, minus what this slice ports. The inventory is derived from the",
        "pinned source tree by `scripts/generate_deferred_inventory.py` rather than",
        "typed, and it is verified by set difference rather than against a literal",
        "count, so a module added upstream fails the check until this file is",
        "regenerated.",
        "",
        f"The shim module `{SHIM_FILENAME}` appears in the inventory because it sits",
        "beside the package upstream and belongs to the same surface. It is not",
        "merely deferred: its plugin discovery is specific to Claude Code, so the",
        "portable packaging model replaces it with a build-time bundle rather than",
        "ever porting it.",
        "",
        "## Pinned source",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Source repository | `{pin['source_repository']}` |",
        f"| Source commit | `{pin['source_commit']}` |",
        f"| Fleet Core version | `{pin['source_version']}` |",
        "",
        "Custody does not move. A future change to any module below lands upstream",
        "first and reaches this repository by re-synchronization.",
        "",
        PORTED_HEADING,
        "",
        *_table(ported),
        "",
        DEFERRED_HEADING,
        "",
        *_table(deferred),
        "",
        "## Counts",
        "",
        "| Basis | Python modules | Data files | Total |",
        "|---|---|---|---|",
        "| Upstream inventory | {} | {} | {} |".format(*upstream_counts),
        "| Ported by this package | {} | {} | {} |".format(*ported_counts),
        "| Deferred | {} | {} | {} |".format(*deferred_counts),
        "",
    ]
    return "\n".join(lines)


def parse_rendered_items(text: str, heading: str) -> list[Item]:
    """Read one inventory table back out of a rendered document.

    Used by the hermetic self-check, which has no upstream tree to derive from
    and therefore compares the recorded inventory against the package itself.
    """
    lines = text.splitlines()
    try:
        start = lines.index(heading)
    except ValueError as exc:
        raise InventoryError(f"missing section in inventory document: {heading}") from exc

    items: list[Item] = []
    for line in lines[start + 1 :]:
        if line.startswith("## "):
            break
        match = TABLE_ROW.match(line)
        if match and match.group(1) != "Item":
            items.append(Item(match.group(1), match.group(2)))
    return items


def check_against_source(package_root: Path, source_root: Path, output: Path) -> list[str]:
    """Compare the recorded inventory against a fresh derivation. Writes nothing."""
    upstream = inventory(source_root)
    ported = inventory(package_root)

    errors = [
        f"ported item has no upstream counterpart: {item.name}"
        for item in unknown_ported_items(upstream, ported)
    ]

    if not output.is_file():
        errors.append(f"missing inventory document: {output}")
        return errors

    expected = render(read_pin(package_root), upstream, ported)
    actual = output.read_text(encoding="utf-8")
    if actual == expected:
        return errors

    errors.append(f"inventory out of date: {output}")
    recorded = {item.name for item in parse_rendered_items(actual, DEFERRED_HEADING)}
    derived = {item.name for item in deferred_items(upstream, ported)}
    for name in sorted(derived - recorded):
        errors.append(f"upstream item missing from the inventory: {name}")
    for name in sorted(recorded - derived):
        errors.append(f"inventory names an item the source does not carry: {name}")
    return errors


def self_check(package_root: Path, output: Path) -> list[str]:
    """Verify the recorded inventory against the package, with no upstream tree.

    This is the half of the guarantee that survives a hermetic run. It cannot
    see whether a module was added upstream, but it does catch the inverse and
    likelier local drift: this package porting a module that the recorded
    inventory still lists as deferred, or dropping one it claims to port.
    """
    if not output.is_file():
        return [f"missing inventory document: {output}"]

    text = output.read_text(encoding="utf-8")
    ported = inventory(package_root)
    ported_names = {item.name for item in ported}

    errors: list[str] = []
    recorded_ported = parse_rendered_items(text, PORTED_HEADING)
    recorded_ported_names = {item.name for item in recorded_ported}
    for name in sorted(ported_names - recorded_ported_names):
        errors.append(f"package ports an item the inventory does not record: {name}")
    for name in sorted(recorded_ported_names - ported_names):
        errors.append(f"inventory records a ported item the package does not carry: {name}")

    for item in parse_rendered_items(text, DEFERRED_HEADING):
        if item.name in ported_names:
            errors.append(f"item is listed as deferred but present in the package: {item.name}")
    return errors


def generate(package_root: Path, source_root: Path, output: Path) -> str:
    upstream = inventory(source_root)
    ported = inventory(package_root)
    unknown = unknown_ported_items(upstream, ported)
    if unknown:
        names = ", ".join(item.name for item in unknown)
        raise InventoryError(f"ported items have no upstream counterpart: {names}")
    text = render(read_pin(package_root), upstream, ported)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    return text


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--source",
        type=Path,
        help=(
            "upstream Fleet Core package root at the pinned commit, holding "
            "scripts/fleet_commons/. Omit with --check for the hermetic self-check."
        ),
    )
    parser.add_argument(
        "--package",
        type=Path,
        default=None,
        help="portable Fleet Core package root (default: plugins/fleet-core in this repository)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=f"inventory document to write or verify (default: <package>/{DEFERRED_FILENAME})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify without writing; exit non-zero when the inventory is out of date",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    repository_root = Path(__file__).resolve().parents[1]
    package_root = args.package or repository_root / "plugins" / "fleet-core"
    output = args.output or package_root / DEFERRED_FILENAME

    try:
        if args.check:
            errors = (
                check_against_source(package_root, args.source, output)
                if args.source is not None
                else self_check(package_root, output)
            )
            if errors:
                for error in errors:
                    print(f"ERROR: {error}", file=sys.stderr)
                return 1
            print(f"Deferred inventory check passed: {output}")
            return 0

        if args.source is None:
            parser.error("--source is required to generate; use --check alone to self-check")
        generate(package_root, args.source, output)
    except InventoryError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote deferred inventory: {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
