#!/usr/bin/env python3
"""Rust review adapters, built from review-tools.yaml (issue 153).

Importing this module reads the yaml and builds adapter objects. It does not run a tool.
"""

from __future__ import annotations

import json
import math
import os
import re
import shutil
from collections.abc import Mapping
from pathlib import Path

import yaml

import review_formula
import review_tools
from review_tools import Adapter, Hit, ParseResult, RulePin, ScanContext, ToolGap

_RUST_MARKER_NAMES = frozenset({
    "Cargo.toml", "Cargo.lock",
})
_RUST_SUFFIXES = (".rs",)
_PRUNE_DIRS = frozenset({".git", "target"})
_DENY_CONFIG = "deny.toml"
_CLIPPY_CONFIGS = ("clippy.toml", ".clippy.toml")
_TOOLCHAIN_FILES = ("rust-toolchain.toml", "rust-toolchain")
#: Restated clippy defaults: denying correctness and warning the rest beats a
#: hostile manifest `[lints]` table without changing what fires by default.
_CLIPPY_LEVELS = (
    "-D", "clippy::correctness",
    "-W", "clippy::suspicious",
    "-W", "clippy::style",
    "-W", "clippy::complexity",
    "-W", "clippy::perf",
)
_GENERATED_DENY_CONFIG = """\
# Generated by saga review tools (issue 153): the base commit carries no
# deny.toml, so cargo-deny's defaults apply.
"""

#: Non-vulnerability advisory codes, all a draft medium-low for the sitting.
_NON_VULNERABILITY_CODES = ("unmaintained", "unsound", "notice", "yanked")
_YANKED_PACKAGE = re.compile(r"cargo update -p ([^`\s]+)")
_MUTANT_NAME = re.compile(r"^(.+?):\d+:\d+:\s*(.*)$")
_MACHETE_SECTION = re.compile(r"^(.*?)\s+--\s+(.*?):\s*$")

_ROWS: dict[str, tuple[str, ...]] = {
    "cargo-deny": ("security.dependency-high", "security.dependency-medium-low"),
    "cargo-check": ("correctness.type-error",),
    "clippy": ("correctness.tool-error", "correctness.tool-warning"),
    "cargo-mutants": ("testing.surviving-mutant",),
    "cargo-machete": ("architecture-maintainability.complexity-dead-code-naming",),
    "rustfmt": (),
    "rust-shuffle": ("testing.flaky-order-or-network",),
    "rust-no-network": ("testing.flaky-order-or-network",),
    "rust-coverage": ("testing.uncovered-branch",),
}


def cvss31_score(vector: object) -> float | None:
    """CVSS 3.x base score for a vector string, else None.

    Integer math per the FIRST 3.1 specification, so no float drift. Vectors
    that are not 3.0/3.1, that miss a base metric, or that name an unknown
    value do not score; temporal metrics are ignored. Unscorable means the
    advisory counts as no score, hence high.
    """
    if not isinstance(vector, str):
        return None
    parts = vector.split("/")
    if len(parts) < 2 or parts[0] not in ("CVSS:3.0", "CVSS:3.1"):
        return None
    metrics: dict[str, str] = {}
    for part in parts[1:]:
        name, separator, value = part.partition(":")
        if not separator or not name or not value:
            return None
        metrics[name] = value
    try:
        attack_vector = {"N": 0.85, "A": 0.62, "L": 0.55, "P": 0.2}[metrics["AV"]]
        attack_complexity = {"L": 0.77, "H": 0.44}[metrics["AC"]]
        scope_changed = {"U": False, "C": True}[metrics["S"]]
        if scope_changed:
            privileges = {"N": 0.85, "L": 0.68, "H": 0.5}[metrics["PR"]]
        else:
            privileges = {"N": 0.85, "L": 0.62, "H": 0.27}[metrics["PR"]]
        interaction = {"N": 0.85, "R": 0.62}[metrics["UI"]]
        impact_value = {"H": 0.56, "L": 0.22, "N": 0.0}
        confidentiality = impact_value[metrics["C"]]
        integrity = impact_value[metrics["I"]]
        availability = impact_value[metrics["A"]]
    except KeyError:
        return None
    impact_sub = 1.0 - (1.0 - confidentiality) * (1.0 - integrity) * (1.0 - availability)
    if scope_changed:
        impact = 7.52 * (impact_sub - 0.029) - 3.25 * (impact_sub - 0.02) ** 15
        exploitability = 8.22 * attack_vector * attack_complexity * privileges * interaction
        raw = min(1.08 * (impact + exploitability), 10.0)
    else:
        impact = 6.42 * impact_sub
        exploitability = 8.22 * attack_vector * attack_complexity * privileges * interaction
        raw = min(impact + exploitability, 10.0)
    if impact_sub <= 0.0:
        return 0.0
    # FIRST roundup: the smallest one-decimal number at or above the input.
    scaled = int(round(raw * 100000))
    if scaled % 10000 == 0:
        return scaled / 100000
    return (math.floor(scaled / 10000) + 1) / 10


def _document() -> dict[str, object]:
    loaded = yaml.safe_load(review_tools.TOOL_LIST.read_text(encoding="utf-8"))
    if not isinstance(loaded, dict):
        raise review_tools.RunnerFailure(2, "review-tools.yaml must be an object")
    return loaded


def _walk(root: Path) -> list[Path]:
    """Files under ``root`` with caches and env trees pruned."""
    found: list[Path] = []
    for directory, dirnames, filenames in os.walk(root, followlinks=False):
        for pruned in [name for name in dirnames if name in _PRUNE_DIRS or name == ".git"]:
            dirnames.remove(pruned)
        for name in filenames:
            found.append(Path(directory) / name)
    return found


def _has_markers(root: Path) -> bool:
    for path in _walk(root):
        if path.name in _RUST_MARKER_NAMES:
            return True
    return False


def _files_with(root: Path, suffixes: tuple[str, ...]) -> list[str]:
    return sorted(
        path.relative_to(root).as_posix()
        for path in _walk(root)
        if path.suffix in suffixes
    )


def _base_file(context: ScanContext, name: str) -> Path | None:
    for staged_name, staged_path in context.base_files:
        if staged_name == name:
            return staged_path
    return None


def _stage_base(context: ScanContext, name: str, dest: str | None = None) -> Path | None:
    """Copy the staged base file over the stripped name in the scan tree."""
    staged = _base_file(context, name)
    if staged is None:
        return None
    target = context.root / (dest or name)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(staged.read_bytes())
    return target


def _stage_first_base(context: ScanContext, names: tuple[str, ...]) -> Path | None:
    for name in names:
        staged = _stage_base(context, name)
        if staged is not None:
            return staged
    return None


def _stage_toolchain(context: ScanContext) -> None:
    for name in _TOOLCHAIN_FILES:
        _stage_base(context, name)


def _invoke_cargo_deny(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    if not (context.root / "Cargo.lock").is_file():
        return []
    staged = _stage_base(context, _DENY_CONFIG)
    if staged is None:
        staged = context.root / _DENY_CONFIG
        staged.write_text(_GENERATED_DENY_CONFIG, encoding="utf-8")
    return [
        "cargo-deny", "--format", "json", "--config", str(staged),
        "check", "advisories",
    ]


def _deny_advisory_ids(advisory: Mapping[str, object]) -> list[str]:
    found: list[str] = []
    ident = advisory.get("id")
    if isinstance(ident, str) and ident:
        found.append(ident)
    aliases = advisory.get("aliases") or []
    if isinstance(aliases, list):
        for alias in aliases:
            if isinstance(alias, str) and alias and alias not in found:
                found.append(alias)
    return found


def _parse_cargo_deny(text: str) -> ParseResult:
    hits: list[Hit] = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(entry, dict) or entry.get("type") != "diagnostic":
            continue
        fields = entry.get("fields")
        if not isinstance(fields, dict):
            continue
        if str(fields.get("severity") or "").lower() == "note":
            # Base-config ignores report at note severity; the base config is
            # trusted, so ignored advisories stay silent.
            continue
        code = str(fields.get("code") or "")
        advisory = fields.get("advisory")
        if code == "vulnerability":
            if not isinstance(advisory, dict):
                continue
            identifiers = _deny_advisory_ids(advisory)
            if not identifiers:
                continue
            score = cvss31_score(advisory.get("cvss"))
            package = str(advisory.get("package") or "unknown package")
            hits.append(Hit(
                rule_id=identifiers[0],
                path="Cargo.lock",
                statement=(
                    f"cargo-deny reports {identifiers[0]} in {package}."
                ),
                anchor=identifiers[0],
                advisory_ids=tuple(identifiers),
                score=score,
                row=review_formula.dependency_row(score),
                whole_project=True,
            ))
        elif code in _NON_VULNERABILITY_CODES:
            if isinstance(advisory, dict):
                identifiers = _deny_advisory_ids(advisory)
                if not identifiers:
                    continue
                rule_id = identifiers[0]
                package = str(advisory.get("package") or "unknown package")
                statement = f"cargo-deny reports {code} {rule_id} in {package}."
            else:
                match = _YANKED_PACKAGE.search(str(fields.get("message") or ""))
                package = match.group(1) if match else "unknown package"
                rule_id = f"yanked-{package}"
                identifiers = []
                statement = f"cargo-deny reports yanked {package}."
            hits.append(Hit(
                rule_id=rule_id,
                path="Cargo.lock",
                statement=statement,
                anchor=rule_id,
                advisory_ids=tuple(identifiers),
                row="security.dependency-medium-low",
                whole_project=True,
            ))
    return ParseResult(tuple(hits))


def _primary_span(message: Mapping[str, object]) -> Mapping[str, object] | None:
    spans = message.get("spans") or []
    if not isinstance(spans, list):
        return None
    for span in spans:
        if isinstance(span, dict) and span.get("is_primary"):
            return span
    for span in spans:
        if isinstance(span, dict):
            return span
    return None


def _compiler_messages(text: str) -> list[dict[str, object]]:
    """compiler-message payloads from a cargo JSON stream, in order."""
    found: list[dict[str, object]] = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(entry, dict) or entry.get("reason") != "compiler-message":
            continue
        message = entry.get("message")
        if isinstance(message, dict):
            found.append(message)
    return found


def _invoke_cargo_check(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    if not _files_with(context.root, _RUST_SUFFIXES):
        return []
    _stage_toolchain(context)
    return ["cargo", "check", "--locked", "--message-format=json"]


def _parse_cargo_check(text: str) -> ParseResult:
    hits: list[Hit] = []
    for message in _compiler_messages(text):
        if str(message.get("level") or "") != "error":
            continue
        code = message.get("code")
        rule_id = code.get("code") if isinstance(code, dict) else None
        rule_id = str(rule_id) if rule_id else "rustc-error"
        span = _primary_span(message)
        path = str((span or {}).get("file_name") or ".")
        try:
            start = int((span or {}).get("line_start") or 0) or None
        except (TypeError, ValueError):
            start = None
        try:
            end = int((span or {}).get("line_end") or 0) or None
        except (TypeError, ValueError):
            end = None
        detail = str(message.get("message") or "").strip()
        hits.append(Hit(
            rule_id=rule_id,
            path=path,
            statement=f"rustc {rule_id}: {detail}.",
            anchor=f"{rule_id}: {detail}",
            start=start,
            end=end or start,
            row="correctness.type-error",
            whole_project=True,
        ))
    return ParseResult(tuple(hits))


def _invoke_clippy(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    if not _files_with(context.root, _RUST_SUFFIXES):
        return []
    _stage_toolchain(context)
    _stage_first_base(context, _CLIPPY_CONFIGS)
    return [
        "cargo-clippy", "clippy", "--locked", "--message-format=json",
        "--", *_CLIPPY_LEVELS,
    ]


def _parse_clippy(text: str) -> ParseResult:
    hits: list[Hit] = []
    for message in _compiler_messages(text):
        level = str(message.get("level") or "")
        if level not in ("error", "warning"):
            continue
        code = message.get("code")
        name = code.get("code") if isinstance(code, dict) else None
        name = str(name) if name else ""
        if level == "error" and not name.startswith("clippy::"):
            # Rustc errors belong to cargo-check; without this split the same
            # error would arrive twice.
            continue
        rule_id = name or "rustc-warning"
        span = _primary_span(message)
        path = str((span or {}).get("file_name") or ".")
        try:
            start = int((span or {}).get("line_start") or 0) or None
        except (TypeError, ValueError):
            start = None
        try:
            end = int((span or {}).get("line_end") or 0) or None
        except (TypeError, ValueError):
            end = None
        detail = str(message.get("message") or "").strip()
        hits.append(Hit(
            rule_id=rule_id,
            path=path,
            statement=f"clippy {rule_id}: {detail}.",
            anchor=f"{rule_id}: {detail}",
            start=start,
            end=end or start,
            level="error" if level == "error" else "warning",
        ))
    return ParseResult(tuple(hits))


def _invoke_cargo_mutants(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    if not _files_with(context.root, _RUST_SUFFIXES):
        return []
    _stage_toolchain(context)
    argv = ["cargo-mutants", "mutants", "-C", "--locked"]
    if shutil.which("cargo-nextest") is not None:
        argv.extend(["--test-tool", "nextest"])
    return argv


def _parse_cargo_mutants(text: str) -> ParseResult:
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError("cargo-mutants outcomes are not json") from exc
    if not isinstance(data, dict):
        raise ValueError("cargo-mutants outcomes must be an object")
    outcomes = data.get("outcomes") or []
    if not isinstance(outcomes, list):
        raise ValueError("cargo-mutants outcomes must be a list")
    hits: list[Hit] = []
    for outcome in outcomes:
        if not isinstance(outcome, dict):
            continue
        if str(outcome.get("summary") or "") != "MissedMutant":
            continue
        scenario = outcome.get("scenario") or {}
        mutant = scenario.get("Mutant") if isinstance(scenario, dict) else None
        if not isinstance(mutant, dict):
            continue
        name = str(mutant.get("name") or "mutant")
        match = _MUTANT_NAME.match(name)
        anchor = match.group(2).strip() if match else name
        path = str(mutant.get("file") or ".")
        span = mutant.get("span") or {}
        begin = span.get("start") if isinstance(span, dict) else None
        finish = span.get("end") if isinstance(span, dict) else None
        try:
            start = int((begin or {}).get("line") or 0) or None
        except (TypeError, ValueError):
            start = None
        try:
            end = int((finish or {}).get("line") or 0) or None
        except (TypeError, ValueError):
            end = None
        hits.append(Hit(
            rule_id="surviving-mutant",
            path=path,
            statement=f"cargo-mutants mutant survived: {name}.",
            anchor=anchor,
            start=start,
            end=end or start,
            row="testing.surviving-mutant",
        ))
    return ParseResult(tuple(hits))


def _invoke_cargo_machete(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    return ["cargo-machete"]


def _parse_cargo_machete(text: str) -> ParseResult:
    row = "architecture-maintainability.complexity-dead-code-naming"
    hits: list[Hit] = []
    manifest: str | None = None
    for line in text.splitlines():
        section = _MACHETE_SECTION.match(line)
        if section is not None:
            manifest = section.group(2).strip()
            continue
        name = line.strip()
        if manifest is None or not name or line[:1] not in (" ", "\t"):
            continue
        hits.append(Hit(
            rule_id="unused-dependency",
            path=manifest,
            statement=f"cargo-machete reports unused dependency {name}.",
            anchor=f"dependency {name}",
            row=row,
            whole_project=True,
        ))
    return ParseResult(tuple(hits))


def _invoke_rustfmt(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    return ["cargo", "fmt", "--all"]


def _parse_empty(_text: str) -> ParseResult:
    return ParseResult(())


def _invoke_rust_shuffle(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    raise ToolGap("known-gap", "testing.flaky-order-or-network")


def _invoke_rust_no_network(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    raise ToolGap("known-gap", "testing.flaky-order-or-network")


def _rules(row: Mapping[str, object]) -> tuple[RulePin, ...]:
    rules = row.get("rules") or []
    if not isinstance(rules, list):
        return ()
    pins = []
    for entry in rules:
        if not isinstance(entry, dict):
            continue
        pins.append(RulePin(
            pack=entry.get("pack"),
            sha256=entry.get("sha256"),
            path=entry.get("path"),
        ))
    return tuple(pins)


def _level_map(row: Mapping[str, object]) -> tuple[tuple[str, str], ...]:
    mapping = row.get("level_map") or {}
    if not isinstance(mapping, dict):
        return ()
    return tuple((str(key), str(value)) for key, value in mapping.items())


def _build(document: Mapping[str, object]) -> list[Adapter]:
    tools = document.get("tools")
    if not isinstance(tools, list):
        raise review_tools.RunnerFailure(2, "review-tools.yaml tools must be a list")
    invoke = {
        "cargo-deny": _invoke_cargo_deny,
        "cargo-check": _invoke_cargo_check,
        "clippy": _invoke_clippy,
        "cargo-mutants": _invoke_cargo_mutants,
        "cargo-machete": _invoke_cargo_machete,
        "rustfmt": _invoke_rustfmt,
        "rust-shuffle": _invoke_rust_shuffle,
        "rust-no-network": _invoke_rust_no_network,
        "rust-coverage": lambda _context: [],
    }
    parse = {
        "cargo-deny": _parse_cargo_deny,
        "cargo-check": _parse_cargo_check,
        "clippy": _parse_clippy,
        "cargo-mutants": _parse_cargo_mutants,
        "cargo-machete": _parse_cargo_machete,
        "rustfmt": _parse_empty,
        "rust-shuffle": _parse_empty,
        "rust-no-network": _parse_empty,
        "rust-coverage": _parse_empty,
    }
    built: list[Adapter] = []
    for row in tools:
        if not isinstance(row, dict):
            continue
        tool_id = str(row.get("id") or "")
        if tool_id not in invoke:
            continue
        gap = row.get("gap_until_present")
        built.append(Adapter(
            id=tool_id,
            tool=str(row.get("tool") or ""),
            invoke=invoke[tool_id],
            parse=parse[tool_id],
            languages=tuple(str(item) for item in (row.get("languages") or ["*"])),
            rows=_ROWS[tool_id],
            comparison=str(row.get("comparison") or "lines"),
            lens=str(row.get("lens") or "correctness"),
            type_checker=bool(row.get("type_checker")),
            mutation=bool(row.get("mutation")),
            mode=str(row.get("mode") or "report"),
            timeout_seconds=int(row.get("timeout_seconds") or 120),
            platforms=tuple(str(item) for item in (row.get("platforms") or ())),
            env_dirs=tuple(str(item) for item in (row.get("env_dirs") or ())),
            lockfiles=tuple(str(item) for item in (row.get("lockfiles") or ())),
            version_args=tuple(str(item) for item in (row.get("version_args") or ("--version",))),
            default_version=str(row.get("default_version") or "not-recorded"),
            gap_path=str(gap) if isinstance(gap, str) else None,
            gap_rows=(),
            curated_rules=tuple(str(item) for item in (row.get("curated_block_rules") or ())),
            level_map=_level_map(row),
            rules=_rules(row),
            stream=str(row.get("stream") or "stdout"),
            report_file=str(row.get("report_file")) if row.get("report_file") else None,
            silent_ok=bool(row.get("silent_ok")),
            gap_first=bool(row.get("gap_first")),
            base_files=tuple(str(item) for item in (row.get("base_files") or ())),
            local_bins=tuple(str(item) for item in (row.get("local_bins") or ())),
        ))
    return built


ADAPTERS: tuple[Adapter, ...] = tuple(_build(_document()))
