#!/usr/bin/env python3
"""Dart review adapters, built from review-tools.yaml (issue 153).

Importing this module reads the yaml and builds adapter objects. It does not run a tool.
"""

from __future__ import annotations

import json
import os
import re
from collections.abc import Mapping
from pathlib import Path

import yaml

import review_formula
import review_tools
from review_tools import Adapter, Hit, ParseResult, RulePin, ScanContext, ToolGap

_DART_MARKER_NAMES = frozenset({
    "pubspec.yaml", "pubspec.lock",
})
_DART_SUFFIXES = (".dart",)
_PRUNE_DIRS = frozenset({".git", ".dart_tool"})
_ANALYSIS_OPTIONS = "analysis_options.yaml"
_PUBSPEC = "pubspec.yaml"
# The dependency keys whose presence means the tree needs package resolution.
_PUBSPEC_DEP_KEYS = ("dependencies", "dev_dependencies", "dependency_overrides")

#: Generated analysis options, staged when the base commit has none (KTD4).
#: Dart's own core lint set, copied from package:lints 6.1.0 core.yaml so the
#: default needs no installed package. `dart analyze` resolves no includes.
_GENERATED_ANALYSIS_OPTIONS = """\
# Generated by saga review tools (issue 153): the base commit carries no
# analysis options, so the core lint set applies. A project that wants more
# (or less) says so with its own analysis_options.yaml.
linter:
  rules:
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - collection_methods_unrelated_type
    - curly_braces_in_flow_control_structures
    - dangling_library_doc_comments
    - depend_on_referenced_packages
    - empty_catches
    - file_names
    - hash_and_equals
    - implicit_call_tearoffs
    - library_annotations
    - no_duplicate_case_values
    - no_wildcard_variable_uses
    - non_constant_identifier_names
    - null_check_on_nullable_type_parameter
    - prefer_generic_function_type_aliases
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - secure_pubspec_urls
    - strict_top_level_inference
    - type_literal_in_constant_pattern
    - unintended_html_in_doc_comment
    - unnecessary_overrides
    - unrelated_type_equality_checks
    - use_string_in_part_of_directives
    - valid_regexps
    - void_checks
"""

_ANALYZE_LINE = re.compile(
    r"^\s*(error|warning|info)\s+-\s+(.+?):(\d+):(\d+)\s+-\s+(.*)\s+-\s+(\S+)\s*$"
)
_SHUFFLE_SEED = re.compile(
    r"Shuffling test order with --test-randomize-ordering-seed=(\d+)"
)
_SHUFFLE_FAIL = re.compile(r"^\d+:\d+ \+\d+(?: -\d+)?: (.+?) \[E\]\s*$", re.MULTILINE)

_ROWS: dict[str, tuple[str, ...]] = {
    "dart-analyze": (
        "correctness.type-error",
        "correctness.tool-warning",
        "correctness.tool-style",
    ),
    "mutate4dart": ("testing.surviving-mutant",),
    "dart-shuffle": ("testing.flaky-order-or-network",),
    "dart-format": (),
    "dart-no-network": ("testing.flaky-order-or-network",),
    "dart-coverage": ("testing.uncovered-branch",),
}


def _document() -> dict[str, object]:
    loaded = yaml.safe_load(review_tools.TOOL_LIST.read_text(encoding="utf-8"))
    if not isinstance(loaded, dict):
        raise review_tools.RunnerFailure(2, "review-tools.yaml must be an object")
    return loaded


def _walk(root: Path) -> list[Path]:
    """Files under ``root`` with caches and env trees pruned."""
    found: list[Path] = []
    for directory, dirnames, filenames in os.walk(root, followlinks=False):
        for pruned in [name for name in dirnames if name in _PRUNE_DIRS or name == ".git"]:
            dirnames.remove(pruned)
        for name in filenames:
            found.append(Path(directory) / name)
    return found


def _has_markers(root: Path) -> bool:
    for path in _walk(root):
        if path.name in _DART_MARKER_NAMES:
            return True
    return False


def _files_with(root: Path, suffixes: tuple[str, ...]) -> list[str]:
    return sorted(
        path.relative_to(root).as_posix()
        for path in _walk(root)
        if path.suffix in suffixes
    )


def _base_file(context: ScanContext, name: str) -> Path | None:
    for staged_name, staged_path in context.base_files:
        if staged_name == name:
            return staged_path
    return None


def _stage_base(context: ScanContext, name: str, dest: str | None = None) -> Path | None:
    """Copy the staged base file over the stripped name in the scan tree."""
    staged = _base_file(context, name)
    if staged is None:
        return None
    target = context.root / (dest or name)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(staged.read_bytes())
    return target


def _base_pubspec(context: ScanContext) -> dict[str, object]:
    staged = _base_file(context, _PUBSPEC)
    if staged is None:
        return {}
    try:
        data = yaml.safe_load(staged.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return {}
    return data if isinstance(data, dict) else {}


def _declared_dependencies(context: ScanContext) -> bool:
    package = _base_pubspec(context)
    for key in _PUBSPEC_DEP_KEYS:
        value = package.get(key)
        if isinstance(value, dict) and value:
            return True
    return False


def _has_test_dep(context: ScanContext) -> bool:
    package = _base_pubspec(context)
    for key in ("dependencies", "dev_dependencies"):
        value = package.get(key)
        if isinstance(value, dict) and "test" in value:
            return True
    return False


def _needs_resolution(context: ScanContext, row: str) -> None:
    """Decline when declared dependencies have no resolved `.dart_tool`."""
    if _declared_dependencies(context) and not (context.root / ".dart_tool").is_dir():
        raise ToolGap("deps-missing", row)


def _invoke_dart_analyze(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    if not _files_with(context.root, _DART_SUFFIXES):
        return []
    _needs_resolution(context, "correctness.type-error")
    if _stage_base(context, _ANALYSIS_OPTIONS) is None:
        target = context.root / _ANALYSIS_OPTIONS
        target.write_text(_GENERATED_ANALYSIS_OPTIONS, encoding="utf-8")
    return ["dart", "analyze"]


def _parse_dart_analyze(text: str) -> ParseResult:
    hits: list[Hit] = []
    for line in text.splitlines():
        match = _ANALYZE_LINE.match(line.strip())
        if match is None:
            continue
        level, path, line_no, _col, message, code = match.groups()
        start = int(line_no)
        statement = f"Dart {code}: {message.strip()}."
        anchor = f"{code}: {message.strip()}"
        if level == "error":
            hits.append(Hit(
                rule_id=code,
                path=path,
                statement=statement,
                anchor=anchor,
                start=start,
                end=start,
                row="correctness.type-error",
                whole_project=True,
            ))
        else:
            hits.append(Hit(
                rule_id=code,
                path=path,
                statement=statement,
                anchor=anchor,
                start=start,
                end=start,
                level="warning" if level == "warning" else "information",
                whole_project=True,
            ))
    return ParseResult(tuple(hits))


def _invoke_mutate4dart(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    if not _files_with(context.root, _DART_SUFFIXES):
        return []
    _needs_resolution(context, "testing.surviving-mutant")
    return ["mutate4dart", "--format", "json", "--no-coverage"]


def _parse_mutate4dart(text: str) -> ParseResult:
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError("mutate4dart output is not json") from exc
    if not isinstance(data, dict):
        raise ValueError("mutate4dart output must be an object")
    methods = data.get("methods") or []
    if not isinstance(methods, list):
        raise ValueError("mutate4dart methods must be a list")
    hits: list[Hit] = []
    for method in methods:
        if not isinstance(method, dict):
            continue
        path = str(method.get("file") or ".")
        seen: dict[str, int] = {}
        mutants = method.get("mutants") or []
        for mutant in mutants if isinstance(mutants, list) else []:
            if not isinstance(mutant, dict):
                continue
            if str(mutant.get("status") or "") != "survived":
                continue
            operator = str(mutant.get("operator") or "mutant")
            try:
                start = int(mutant.get("line") or 0) or None
            except (TypeError, ValueError):
                start = None
            seen[operator] = seen.get(operator, 0) + 1
            hits.append(Hit(
                rule_id="surviving-mutant",
                path=path,
                statement=f"mutate4dart mutant survived: {operator} in {path}.",
                anchor=f"{operator}:{seen[operator]}",
                start=start,
                end=start,
                row="testing.surviving-mutant",
            ))
    return ParseResult(tuple(hits))


def _invoke_dart_shuffle(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    if not _has_test_dep(context):
        return []
    _needs_resolution(context, "testing.flaky-order-or-network")
    return [
        "dart", "test", "--test-randomize-ordering-seed=random",
        "--reporter", "expanded",
    ]


def _parse_dart_shuffle(text: str) -> ParseResult:
    row = "testing.flaky-order-or-network"
    if "No tests ran." in text or "No tests were found." in text:
        return ParseResult((), gap=("no-tests-ran", row))
    seed_match = _SHUFFLE_SEED.search(text)
    seed = seed_match.group(1) if seed_match else "unreported"
    if "Some tests failed." not in text:
        return ParseResult(())
    failures: dict[tuple[str, str | None], None] = {}
    for match in _SHUFFLE_FAIL.finditer(text):
        label = match.group(1).strip()
        path, _, case = label.partition(": ")
        failures[(path.strip() or ".", case.strip() or None)] = None
    if not failures:
        failures[(".", None)] = None
    return ParseResult(tuple(
        Hit(
            rule_id="shuffle-failure",
            path=path,
            statement=(
                f"Dart {'test ' + case + ' ' if case else 'run '}failed "
                f"in random order (seed {seed})."
            ),
            anchor=f"{path} :: {case or 'suite'}",
            row=row,
            whole_project=True,
        )
        for path, case in failures
    ))


def _invoke_dart_format(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    return ["dart", "format", str(context.root)]


def _parse_empty(_text: str) -> ParseResult:
    return ParseResult(())


def _invoke_dart_no_network(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    raise ToolGap("known-gap", "testing.flaky-order-or-network")


def _rules(row: Mapping[str, object]) -> tuple[RulePin, ...]:
    rules = row.get("rules") or []
    if not isinstance(rules, list):
        return ()
    pins = []
    for entry in rules:
        if not isinstance(entry, dict):
            continue
        pins.append(RulePin(
            pack=entry.get("pack"),
            sha256=entry.get("sha256"),
            path=entry.get("path"),
        ))
    return tuple(pins)


def _level_map(row: Mapping[str, object]) -> tuple[tuple[str, str], ...]:
    mapping = row.get("level_map") or {}
    if not isinstance(mapping, dict):
        return ()
    return tuple((str(key), str(value)) for key, value in mapping.items())


def _build(document: Mapping[str, object]) -> list[Adapter]:
    tools = document.get("tools")
    if not isinstance(tools, list):
        raise review_tools.RunnerFailure(2, "review-tools.yaml tools must be a list")
    invoke = {
        "dart-analyze": _invoke_dart_analyze,
        "mutate4dart": _invoke_mutate4dart,
        "dart-shuffle": _invoke_dart_shuffle,
        "dart-format": _invoke_dart_format,
        "dart-no-network": _invoke_dart_no_network,
        "dart-coverage": lambda _context: [],
    }
    parse = {
        "dart-analyze": _parse_dart_analyze,
        "mutate4dart": _parse_mutate4dart,
        "dart-shuffle": _parse_dart_shuffle,
        "dart-format": _parse_empty,
        "dart-no-network": _parse_empty,
        "dart-coverage": _parse_empty,
    }
    built: list[Adapter] = []
    for row in tools:
        if not isinstance(row, dict):
            continue
        tool_id = str(row.get("id") or "")
        if tool_id not in invoke:
            continue
        gap = row.get("gap_until_present")
        built.append(Adapter(
            id=tool_id,
            tool=str(row.get("tool") or ""),
            invoke=invoke[tool_id],
            parse=parse[tool_id],
            languages=tuple(str(item) for item in (row.get("languages") or ["*"])),
            rows=_ROWS[tool_id],
            comparison=str(row.get("comparison") or "lines"),
            lens=str(row.get("lens") or "correctness"),
            type_checker=bool(row.get("type_checker")),
            mutation=bool(row.get("mutation")),
            mode=str(row.get("mode") or "report"),
            timeout_seconds=int(row.get("timeout_seconds") or 120),
            platforms=tuple(str(item) for item in (row.get("platforms") or ())),
            env_dirs=tuple(str(item) for item in (row.get("env_dirs") or ())),
            lockfiles=tuple(str(item) for item in (row.get("lockfiles") or ())),
            version_args=tuple(str(item) for item in (row.get("version_args") or ("--version",))),
            default_version=str(row.get("default_version") or "not-recorded"),
            gap_path=str(gap) if isinstance(gap, str) else None,
            gap_rows=(),
            curated_rules=tuple(str(item) for item in (row.get("curated_block_rules") or ())),
            level_map=_level_map(row),
            rules=_rules(row),
            stream=str(row.get("stream") or "stdout"),
            report_file=str(row.get("report_file")) if row.get("report_file") else None,
            silent_ok=bool(row.get("silent_ok")),
            gap_first=bool(row.get("gap_first")),
            base_files=tuple(str(item) for item in (row.get("base_files") or ())),
            local_bins=tuple(str(item) for item in (row.get("local_bins") or ())),
        ))
    return built


ADAPTERS: tuple[Adapter, ...] = tuple(_build(_document()))
