#!/usr/bin/env python3
"""Swift review adapters, built from review-tools.yaml (issue 153).

Importing this module reads the yaml and builds adapter objects. It does not run a tool.
"""

from __future__ import annotations

import json
import os
import re
import sys
from collections.abc import Mapping
from pathlib import Path

import yaml

import review_formula
import review_tools
from review_tools import Adapter, Hit, ParseResult, RulePin, ScanContext, ToolGap

_SWIFT_MARKER_NAMES = frozenset({
    "Package.swift", "Package.resolved",
})
_SWIFT_SUFFIXES = (".swift",)
_PRUNE_DIRS = frozenset({".git", ".build", ".saga-build"})
_SWIFTLINT_CONFIGS = (".swiftlint.yml", ".swiftlint.yaml")
_MUTER_CONFIGS = ("muter.conf.yml", "muter.conf.yaml", "muter.conf.json")
_GENERATED_SWIFTLINT_CONFIG = """\
# Generated by saga review tools (issue 153): the base commit carries no
# SwiftLint config, so SwiftLint's built-in rules apply.
"""

_ANSI = re.compile(r"\x1b\[[0-9;?]*[ -/]*[@-~]")
_OSC = re.compile(r"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)")
_DIAGNOSTIC = re.compile(r"^(.*?):(\d+):(\d+):\s+(error|warning|note):\s+(.*)$")
_DIAGNOSTIC_ID = re.compile(r"\[#(.*?)\]\s*$")
#: Id fragments that mark a diagnostic as strict concurrency. Precise on
#: purpose: a false match would block on an ordinary warning.
_CONCURRENCY_ID_HINTS = (
    "Isolation", "Sendable", "Sending", "Concurrency", "DataRace", "Actor",
)
#: Message phrases that mark a no-id diagnostic as strict concurrency.
_CONCURRENCY_PHRASES = (
    "data race", "data-race", "sendable", "sending", "concurrent", "isolation",
)

_ROWS: dict[str, tuple[str, ...]] = {
    "swift-compiler": ("correctness.type-error", "correctness.tool-warning"),
    "swiftlint": ("correctness.tool-error", "correctness.tool-warning"),
    "muter": ("testing.surviving-mutant",),
    "swift-format": (),
    "swift-dependency-audit": ("security.dependency-high",),
    "swift-shuffle": ("testing.flaky-order-or-network",),
    "swift-no-network": ("testing.flaky-order-or-network",),
    "swift-coverage": ("testing.uncovered-branch",),
}


def _platform() -> str:
    return sys.platform


def _document() -> dict[str, object]:
    loaded = yaml.safe_load(review_tools.TOOL_LIST.read_text(encoding="utf-8"))
    if not isinstance(loaded, dict):
        raise review_tools.RunnerFailure(2, "review-tools.yaml must be an object")
    return loaded


def _walk(root: Path) -> list[Path]:
    """Files under ``root`` with caches and env trees pruned."""
    found: list[Path] = []
    for directory, dirnames, filenames in os.walk(root, followlinks=False):
        for pruned in [name for name in dirnames if name in _PRUNE_DIRS or name == ".git"]:
            dirnames.remove(pruned)
        for name in filenames:
            found.append(Path(directory) / name)
    return found


def _has_markers(root: Path) -> bool:
    for path in _walk(root):
        if path.name in _SWIFT_MARKER_NAMES:
            return True
    return False


def _files_with(root: Path, suffixes: tuple[str, ...]) -> list[str]:
    return sorted(
        path.relative_to(root).as_posix()
        for path in _walk(root)
        if path.suffix in suffixes
    )


def _base_file(context: ScanContext, name: str) -> Path | None:
    for staged_name, staged_path in context.base_files:
        if staged_name == name:
            return staged_path
    return None


def _stage_base(context: ScanContext, name: str, dest: str | None = None) -> Path | None:
    """Copy the staged base file over the stripped name in the scan tree."""
    staged = _base_file(context, name)
    if staged is None:
        return None
    target = context.root / (dest or name)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(staged.read_bytes())
    return target


def _stage_first_base(context: ScanContext, names: tuple[str, ...]) -> Path | None:
    for name in names:
        staged = _stage_base(context, name)
        if staged is not None:
            return staged
    return None


def _plain(line: str) -> str:
    """A diagnostic line without color escapes and hyperlink wrappers."""
    return _OSC.sub("", _ANSI.sub("", line))


def _diagnostic_id(message: str) -> tuple[str, str | None]:
    """Split trailing `[#Id]` from the message. The id may be compound."""
    match = _DIAGNOSTIC_ID.search(message)
    if match is None:
        return message.strip(), None
    return message[:match.start()].strip(), match.group(1).strip() or None


def _is_concurrency(identifier: str | None, message: str) -> bool:
    if identifier is not None and any(
        hint in identifier for hint in _CONCURRENCY_ID_HINTS
    ):
        return True
    lowered = message.lower()
    return any(phrase in lowered for phrase in _CONCURRENCY_PHRASES)


def _invoke_swift_compiler(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    if not _files_with(context.root, _SWIFT_SUFFIXES):
        return []
    build_path = context.root / ".saga-build"
    return [
        "swift", "build", "--build-path", str(build_path),
        "-Xswiftc", "-strict-concurrency=complete",
    ]


def _parse_swift_compiler(text: str) -> ParseResult:
    hits: list[Hit] = []
    for raw in text.splitlines():
        match = _DIAGNOSTIC.match(_plain(raw).strip())
        if match is None:
            continue
        path, line_no, _col, level, rest = match.groups()
        if level == "note":
            continue
        message, identifier = _diagnostic_id(rest)
        start = int(line_no)
        if level == "error":
            rule_id = identifier or "swift-error"
            anchor = f"{rule_id}: {message}" if message else rule_id
            hits.append(Hit(
                rule_id=rule_id,
                path=path,
                statement=f"swiftc {rule_id}: {message}." if message else f"swiftc {rule_id}.",
                anchor=anchor,
                start=start,
                end=start,
                row="correctness.type-error",
                whole_project=True,
            ))
        elif _is_concurrency(identifier, message):
            rule_id = identifier or "swift-concurrency"
            anchor = f"{rule_id}: {message}" if message else rule_id
            statement = (
                f"swiftc {rule_id} (strict concurrency): {message}."
                if message else f"swiftc {rule_id} (strict concurrency)."
            )
            hits.append(Hit(
                rule_id=rule_id,
                path=path,
                statement=statement,
                anchor=anchor,
                start=start,
                end=start,
                row="correctness.type-error",
                whole_project=True,
            ))
        else:
            rule_id = identifier or "swift-warning"
            anchor = f"{rule_id}: {message}" if message else rule_id
            hits.append(Hit(
                rule_id=rule_id,
                path=path,
                statement=f"swiftc {rule_id}: {message}." if message else f"swiftc {rule_id}.",
                anchor=anchor,
                start=start,
                end=start,
                level="warning",
                whole_project=True,
            ))
    return ParseResult(tuple(hits))


def _invoke_swiftlint(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    if not _files_with(context.root, _SWIFT_SUFFIXES):
        return []
    staged = _stage_first_base(context, _SWIFTLINT_CONFIGS)
    if staged is None:
        staged = context.root / _SWIFTLINT_CONFIGS[0]
        staged.write_text(_GENERATED_SWIFTLINT_CONFIG, encoding="utf-8")
    return ["swiftlint", "lint", "--reporter", "json", "--config", str(staged)]


def _parse_swiftlint(text: str) -> ParseResult:
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError("swiftlint output is not json") from exc
    if not isinstance(data, list):
        raise ValueError("swiftlint output must be a list")
    hits: list[Hit] = []
    for entry in data:
        if not isinstance(entry, dict):
            continue
        rule_id = str(entry.get("rule_id") or "")
        if not rule_id:
            continue
        try:
            start = int(entry.get("line") or 0) or None
        except (TypeError, ValueError):
            start = None
        reason = str(entry.get("reason") or "").strip()
        severity = str(entry.get("severity") or "").lower()
        hits.append(Hit(
            rule_id=rule_id,
            path=str(entry.get("file") or "."),
            statement=f"SwiftLint {rule_id}: {reason}." if reason else f"SwiftLint {rule_id}.",
            anchor=f"{rule_id}: {reason}" if reason else rule_id,
            start=start,
            end=start,
            level="error" if severity == "error" else "warning",
        ))
    return ParseResult(tuple(hits))


def _invoke_muter(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    if _platform() != "darwin":
        raise ToolGap("unsupported-platform", "testing.surviving-mutant")
    staged = _stage_first_base(context, _MUTER_CONFIGS)
    if staged is None:
        raise ToolGap("not-configured", "testing.surviving-mutant")
    return [
        "muter", "run", "--format", "json", "--skip-update-check",
        "--configuration", str(staged),
    ]


def _parse_muter(text: str) -> ParseResult:
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError("muter output is not json") from exc
    if not isinstance(data, dict):
        raise ValueError("muter output must be an object")
    reports = data.get("fileReports") or []
    if not isinstance(reports, list):
        raise ValueError("muter fileReports must be a list")
    hits: list[Hit] = []
    for report in reports:
        if not isinstance(report, dict):
            continue
        applied = report.get("appliedOperators") or []
        if not isinstance(applied, list):
            continue
        seen: dict[str, int] = {}
        for entry in applied:
            if not isinstance(entry, dict):
                continue
            if str(entry.get("testSuiteOutcome") or "") != "passed":
                continue
            point = entry.get("mutationPoint") or {}
            if not isinstance(point, dict):
                continue
            operator = str(point.get("mutationOperatorId") or "mutant")
            position = point.get("position") or {}
            try:
                start = int((position or {}).get("line") or 0) or None
            except (TypeError, ValueError):
                start = None
            seen[operator] = seen.get(operator, 0) + 1
            hits.append(Hit(
                rule_id="surviving-mutant",
                path=str(point.get("filePath") or "."),
                statement=f"Muter mutant survived: {operator}.",
                anchor=f"{operator}:{seen[operator]}",
                start=start,
                end=start,
                level="error",
                row="testing.surviving-mutant",
            ))
    return ParseResult(tuple(hits))


def _invoke_swift_format(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    return ["swift-format", "format", str(context.root)]


def _parse_empty(_text: str) -> ParseResult:
    return ParseResult(())


def _invoke_swift_dependency_audit(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    raise ToolGap("known-gap", "security.dependency-high")


def _invoke_swift_shuffle(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    raise ToolGap("known-gap", "testing.flaky-order-or-network")


def _invoke_swift_no_network(context: ScanContext) -> list[str]:
    if not _has_markers(context.root):
        return []
    raise ToolGap("known-gap", "testing.flaky-order-or-network")


def _rules(row: Mapping[str, object]) -> tuple[RulePin, ...]:
    rules = row.get("rules") or []
    if not isinstance(rules, list):
        return ()
    pins = []
    for entry in rules:
        if not isinstance(entry, dict):
            continue
        pins.append(RulePin(
            pack=entry.get("pack"),
            sha256=entry.get("sha256"),
            path=entry.get("path"),
        ))
    return tuple(pins)


def _level_map(row: Mapping[str, object]) -> tuple[tuple[str, str], ...]:
    mapping = row.get("level_map") or {}
    if not isinstance(mapping, dict):
        return ()
    return tuple((str(key), str(value)) for key, value in mapping.items())


def _build(document: Mapping[str, object]) -> list[Adapter]:
    tools = document.get("tools")
    if not isinstance(tools, list):
        raise review_tools.RunnerFailure(2, "review-tools.yaml tools must be a list")
    invoke = {
        "swift-compiler": _invoke_swift_compiler,
        "swiftlint": _invoke_swiftlint,
        "muter": _invoke_muter,
        "swift-format": _invoke_swift_format,
        "swift-dependency-audit": _invoke_swift_dependency_audit,
        "swift-shuffle": _invoke_swift_shuffle,
        "swift-no-network": _invoke_swift_no_network,
        "swift-coverage": lambda _context: [],
    }
    parse = {
        "swift-compiler": _parse_swift_compiler,
        "swiftlint": _parse_swiftlint,
        "muter": _parse_muter,
        "swift-format": _parse_empty,
        "swift-dependency-audit": _parse_empty,
        "swift-shuffle": _parse_empty,
        "swift-no-network": _parse_empty,
        "swift-coverage": _parse_empty,
    }
    built: list[Adapter] = []
    for row in tools:
        if not isinstance(row, dict):
            continue
        tool_id = str(row.get("id") or "")
        if tool_id not in invoke:
            continue
        gap = row.get("gap_until_present")
        built.append(Adapter(
            id=tool_id,
            tool=str(row.get("tool") or ""),
            invoke=invoke[tool_id],
            parse=parse[tool_id],
            languages=tuple(str(item) for item in (row.get("languages") or ["*"])),
            rows=_ROWS[tool_id],
            comparison=str(row.get("comparison") or "lines"),
            lens=str(row.get("lens") or "correctness"),
            type_checker=bool(row.get("type_checker")),
            mutation=bool(row.get("mutation")),
            mode=str(row.get("mode") or "report"),
            timeout_seconds=int(row.get("timeout_seconds") or 120),
            platforms=tuple(str(item) for item in (row.get("platforms") or ())),
            env_dirs=tuple(str(item) for item in (row.get("env_dirs") or ())),
            lockfiles=tuple(str(item) for item in (row.get("lockfiles") or ())),
            version_args=tuple(str(item) for item in (row.get("version_args") or ("--version",))),
            default_version=str(row.get("default_version") or "not-recorded"),
            gap_path=str(gap) if isinstance(gap, str) else None,
            gap_rows=(),
            curated_rules=tuple(str(item) for item in (row.get("curated_block_rules") or ())),
            level_map=_level_map(row),
            rules=_rules(row),
            stream=str(row.get("stream") or "stdout"),
            report_file=str(row.get("report_file")) if row.get("report_file") else None,
            silent_ok=bool(row.get("silent_ok")),
            gap_first=bool(row.get("gap_first")),
            base_files=tuple(str(item) for item in (row.get("base_files") or ())),
            local_bins=tuple(str(item) for item in (row.get("local_bins") or ())),
        ))
    return built


ADAPTERS: tuple[Adapter, ...] = tuple(_build(_document()))
